name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Laravel
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------
      # Checkout Repository
      # ----------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------
      # Deploy Full Laravel Project
      # ----------------------------------------
      - name: Deploy Laravel Application
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21

          server-dir: /laravel-app/

          state-name: .ftp-deploy-laravel-state.json

          dangerous-clean-slate: false

          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**

      # ----------------------------------------
      # Deploy Public Directory
      # ----------------------------------------
      - name: Deploy Public Directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21

          local-dir: ./public/
          server-dir: /dev.webiro.ir/

          state-name: .ftp-deploy-public-state.json

          dangerous-clean-slate: false