name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------
      # Checkout
      # ----------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------
      # PHP
      # ----------------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, intl, pdo_mysql
          tools: composer
          coverage: none

      # ----------------------------------------
      # Composer
      # ----------------------------------------
      - name: Install Composer dependencies
        run: |
          composer install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --no-progress \
            --optimize-autoloader

      # ----------------------------------------
      # Node.js
      # ----------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # ----------------------------------------
      # NPM
      # ----------------------------------------
      - name: Install NPM dependencies
        run: npm ci

      # ----------------------------------------
      # Vite
      # ----------------------------------------
      - name: Build frontend assets
        run: npm run build

      # ----------------------------------------
      # FTP Deploy
      # ----------------------------------------
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21

          server-dir: /dev.webiro.ir/

          state-name: .ftp-deploy-sync-state.json

          dangerous-clean-slate: false

          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/storage/**
            **/tests/**
            **/.env
            **/.env.*
            **/phpunit.xml
            **/README.md
            **/vite.config.js